name: Testing
on:
  push:
    branches:
    - main
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 13.3.1
        run: sudo xcode-select -switch /Applications/Xcode_13.3.1.app
      - name: setup-cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.11.3
      - name: Install pods
        run: pod install
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
